import { useState } from 'react';
import { Tile, Button, Select, SelectItem, Tag } from '@carbon/react';
import { ArrowUp, ArrowDown, Locked, Unlocked } from '@carbon/icons-react';
import { APPROVERS, makeAILabel } from './aiLabel';

function LevelTag({ level, title, requirement }) {
  return (
    <div className="chat-level-tag">
      <Tag type="high-contrast">{level}</Tag>
      <div>
        <p className="chat-level-title">{title}</p>
        <p className="chat-level-requirement">{requirement}</p>
      </div>
    </div>
  );
}

function Trend({ direction, value }) {
  const Icon = direction === 'up' ? ArrowUp : ArrowDown;
  return (
    <span className={`anomaly-trend anomaly-trend--${direction}`}>
      <Icon size={16} />
      {value}
    </span>
  );
}

function O1Anomaly() {
  const aiLabel = makeAILabel({
    heading: 'Anomaly detected',
    body: 'Detected automatically by comparing this week to the trailing 8-week average for this region. No review is required before display.',
    kind: 'inline',
    size: 'xs',
  });

  return (
    <section className="anomaly-scenario">
      <LevelTag
        level="O1"
        title="Minor traffic dip"
        requirement="Ship requirement: disclosure only, no confirmation gate."
      />
      <Tile className="anomaly-tile">
        <div className="anomaly-tile-header">
          <p className="anomaly-metric">Page views &mdash; APAC (low-priority region)</p>
          {aiLabel}
        </div>
        <p className="anomaly-value">12,480</p>
        <Trend direction="down" value="6% vs. 8-week avg" />
        <p className="anomaly-note">
          Flagged as a minor deviation. No action recommended.
        </p>
      </Tile>
    </section>
  );
}

function O2Anomaly() {
  const [dismissed, setDismissed] = useState(false);

  const aiLabel = makeAILabel({
    heading: 'Explanation generated',
    body: 'This attribution was generated by correlating the spend spike with active campaign schedules. A human can dismiss it if it looks wrong.',
    kind: 'inline',
    size: 'xs',
    revertActive: dismissed,
    onRevertClick: () => setDismissed(false),
  });

  return (
    <section className="anomaly-scenario">
      <LevelTag
        level="O2"
        title="Spend spike, AI-attributed"
        requirement="Ship requirement: disclosure plus a revert-to-AI-content interaction."
      />
      <Tile className="anomaly-tile">
        <div className="anomaly-tile-header">
          <p className="anomaly-metric">Ad spend &mdash; EU region</p>
          {aiLabel}
        </div>
        <p className="anomaly-value">$18,240</p>
        <Trend direction="up" value="34% vs. 8-week avg" />
        <p className="anomaly-note">
          {dismissed
            ? 'AI attribution dismissed. Shown as an unexplained anomaly.'
            : 'Attributed to the "Summer Sale" campaign entering its bidding-boost phase.'}
        </p>
        <div className="anomaly-controls">
          <Tag type={dismissed ? 'gray' : 'blue'}>
            {dismissed ? 'Unexplained' : 'AI-attributed'}
          </Tag>
          <Button
            kind="tertiary"
            size="sm"
            onClick={() => setDismissed(true)}
            disabled={dismissed}
          >
            Dismiss AI explanation
          </Button>
        </div>
      </Tile>
    </section>
  );
}

function O3Anomaly() {
  const [decision, setDecision] = useState(null);

  const aiLabel = makeAILabel({
    heading: 'Recommendation generated',
    body: 'Recommended because this campaign has spent 3x its daily budget with a conversion rate 90% below account average. Nothing happens until confirmed.',
    kind: 'inline',
    size: 'xs',
  });

  return (
    <section className="anomaly-scenario">
      <LevelTag
        level="O3"
        title="Underperforming campaign"
        requirement="Ship requirement: explicit Confirm or Cancel before the action takes effect."
      />
      <Tile className="anomaly-tile">
        <div className="anomaly-tile-header">
          <p className="anomaly-metric">Campaign &ldquo;Spring Clearance&rdquo;</p>
          {aiLabel}
        </div>
        <p className="anomaly-value">0.2% conversion rate</p>
        <Trend direction="down" value="90% below account average" />
        <p className="anomaly-note">Recommended action: pause this campaign.</p>
        {!decision && (
          <div className="anomaly-controls">
            <Button kind="primary" size="sm" onClick={() => setDecision('confirmed')}>
              Confirm
            </Button>
            <Button kind="secondary" size="sm" onClick={() => setDecision('cancelled')}>
              Cancel
            </Button>
          </div>
        )}
        {decision && (
          <p className={`oversight-result ${decision}`}>
            {decision === 'confirmed'
              ? 'Campaign paused.'
              : 'Recommendation dismissed. Campaign left running.'}
          </p>
        )}
      </Tile>
    </section>
  );
}

function O4Anomaly() {
  const [approver, setApprover] = useState('');
  const [confirmed, setConfirmed] = useState(false);

  const aiLabel = makeAILabel({
    heading: 'Fraud risk flagged',
    body: 'Flagged due to a burst of high-value transactions from a new device and location. Requires sign-off from a named approver before the account is frozen.',
    kind: 'inline',
    size: 'xs',
  });

  return (
    <section className="anomaly-scenario">
      <LevelTag
        level="O4"
        title="Suspected fraud on account"
        requirement="Ship requirement: confirm action stays disabled until a specific named approver is selected."
      />
      <Tile className="anomaly-tile">
        <div className="anomaly-tile-header">
          <p className="anomaly-metric">Account #A-88213</p>
          {aiLabel}
        </div>
        <p className="anomaly-value">7 transactions in 4 minutes</p>
        <Trend direction="up" value="$6,400 total, new device" />
        <p className="anomaly-note">Recommended action: freeze this account.</p>
        <div className="anomaly-controls">
          <Select
            id="dash-o4-approver"
            labelText="Approver"
            value={approver}
            onChange={(e) => setApprover(e.target.value)}
          >
            <SelectItem value="" text="Select an approver" />
            {APPROVERS.map((name) => (
              <SelectItem key={name} value={name} text={name} />
            ))}
          </Select>
          <Button
            kind="primary"
            size="sm"
            disabled={!approver || confirmed}
            onClick={() => setConfirmed(true)}
          >
            Freeze account
          </Button>
        </div>
        {confirmed && (
          <p className="oversight-result confirmed">
            Account frozen by {approver}.
          </p>
        )}
      </Tile>
    </section>
  );
}

function O5Anomaly() {
  const [reviewer1, setReviewer1] = useState('');
  const [reviewer2, setReviewer2] = useState('');
  const [auditLog, setAuditLog] = useState([]);
  const [unlocked, setUnlocked] = useState(false);

  const bothSelected = reviewer1 && reviewer2;
  const distinctReviewers = bothSelected && reviewer1 !== reviewer2;

  const logApproval = (label, name) => {
    setAuditLog((log) => [
      ...log,
      { label, name, timestamp: new Date().toLocaleTimeString() },
    ]);
  };

  const handleReviewer1Change = (e) => {
    const name = e.target.value;
    setReviewer1(name);
    setUnlocked(false);
    if (name) logApproval('Reviewer 1', name);
  };

  const handleReviewer2Change = (e) => {
    const name = e.target.value;
    setReviewer2(name);
    setUnlocked(false);
    if (name) logApproval('Reviewer 2', name);
  };

  const handleUnlock = () => {
    setUnlocked(true);
    logApproval('Action unlocked', `${reviewer1} + ${reviewer2}`);
  };

  const aiLabel = makeAILabel({
    heading: 'Critical anomaly flagged',
    body: 'Flagged because this volume of data egress to an unrecognized external endpoint is unprecedented for this org. Requires two different named reviewers before API access is revoked.',
    kind: 'inline',
    size: 'xs',
  });

  return (
    <section className="anomaly-scenario">
      <LevelTag
        level="O5"
        title="Unusual data egress, org-wide"
        requirement="Ship requirement: two different named reviewers required to unlock, with each approval logged to a visible audit trail."
      />
      <Tile className="anomaly-tile">
        <div className="anomaly-tile-header">
          <p className="anomaly-metric">Org-wide API egress</p>
          {aiLabel}
        </div>
        <p className="anomaly-value">840 GB in 10 minutes</p>
        <Trend direction="up" value="140x normal peak, unrecognized endpoint" />
        <p className="anomaly-note">Recommended action: revoke all API access org-wide.</p>
        <div className="anomaly-controls">
          <Select
            id="dash-o5-reviewer1"
            labelText="Reviewer 1"
            value={reviewer1}
            onChange={handleReviewer1Change}
          >
            <SelectItem value="" text="Select a reviewer" />
            {APPROVERS.map((name) => (
              <SelectItem key={name} value={name} text={name} />
            ))}
          </Select>
          <Select
            id="dash-o5-reviewer2"
            labelText="Reviewer 2"
            value={reviewer2}
            onChange={handleReviewer2Change}
          >
            <SelectItem value="" text="Select a reviewer" />
            {APPROVERS.map((name) => (
              <SelectItem key={name} value={name} text={name} />
            ))}
          </Select>
          <Button
            kind="primary"
            size="sm"
            disabled={!distinctReviewers || unlocked}
            onClick={handleUnlock}
            renderIcon={distinctReviewers ? Unlocked : Locked}
          >
            {unlocked ? 'Unlocked' : 'Unlock action'}
          </Button>
        </div>
        {bothSelected && !distinctReviewers && (
          <p className="oversight-result cancelled">
            Reviewer 1 and Reviewer 2 must be different people.
          </p>
        )}
        {unlocked && (
          <p className="oversight-result confirmed">
            API access revoked org-wide.
          </p>
        )}
        <div className="audit-trail">
          <h4>Audit trail</h4>
          {auditLog.length === 0 ? (
            <p className="audit-empty">No approvals logged yet.</p>
          ) : (
            <ul>
              {auditLog.map((entry, i) => (
                <li key={i}>
                  <span className="audit-timestamp">{entry.timestamp}</span>
                  <span>
                    {entry.label}: {entry.name}
                  </span>
                </li>
              ))}
            </ul>
          )}
        </div>
      </Tile>
    </section>
  );
}

function DashboardDemo() {
  return (
    <div className="dashboard-demo">
      <O1Anomaly />
      <O2Anomaly />
      <O3Anomaly />
      <O4Anomaly />
      <O5Anomaly />
    </div>
  );
}

export default DashboardDemo;
