import { useState } from 'react';
import { Tile, Button, Select, SelectItem, Tag } from '@carbon/react';
import { Locked, Unlocked } from '@carbon/icons-react';
import { APPROVERS, makeAILabel } from './aiLabel';

function LevelTag({ level, title, requirement }) {
  return (
    <div className="chat-level-tag">
      <Tag type="high-contrast">{level}</Tag>
      <div>
        <p className="chat-level-title">{title}</p>
        <p className="chat-level-requirement">{requirement}</p>
      </div>
    </div>
  );
}

function O1VisitSummary() {
  const aiLabel = makeAILabel({
    heading: 'Note generated',
    body: 'Drafted from the visit transcript for the chart. Not a diagnosis or treatment decision — shown for the clinician’s reference only.',
    kind: 'inline',
    size: 'xs',
  });

  return (
    <section className="anomaly-scenario">
      <LevelTag
        level="O1"
        title="Visit note summary"
        requirement="Ship requirement: disclosure only, no confirmation gate."
      />
      <Tile className="anomaly-tile">
        <div className="anomaly-tile-header">
          <p className="anomaly-metric">Patient: J. Alvarez &mdash; Follow-up visit</p>
          {aiLabel}
        </div>
        <p className="anomaly-note">
          Patient reports improved sleep since starting the new dosage two weeks
          ago. No new symptoms noted. Blood pressure stable at 122/78.
        </p>
      </Tile>
    </section>
  );
}

function O2LabInterpretation() {
  const [dismissed, setDismissed] = useState(false);

  const aiLabel = makeAILabel({
    heading: 'Interpretation generated',
    body: 'Generated by comparing this result against the patient’s reference range and prior labs. The clinician can dismiss it if it doesn’t fit the clinical picture.',
    kind: 'inline',
    size: 'xs',
    revertActive: dismissed,
    onRevertClick: () => setDismissed(false),
  });

  return (
    <section className="anomaly-scenario">
      <LevelTag
        level="O2"
        title="Lab result interpretation"
        requirement="Ship requirement: disclosure plus a revert-to-AI-content interaction."
      />
      <Tile className="anomaly-tile">
        <div className="anomaly-tile-header">
          <p className="anomaly-metric">Patient: R. Okonkwo &mdash; TSH panel</p>
          {aiLabel}
        </div>
        <p className="anomaly-value">TSH 6.8 mIU/L</p>
        <p className="anomaly-note">
          {dismissed
            ? 'AI interpretation dismissed. Shown as a raw result pending clinician read.'
            : 'Consistent with subclinical hypothyroidism; consider repeat testing in 6–12 weeks.'}
        </p>
        <div className="anomaly-controls">
          <Tag type={dismissed ? 'gray' : 'blue'}>
            {dismissed ? 'Unreviewed' : 'AI-interpreted'}
          </Tag>
          <Button
            kind="tertiary"
            size="sm"
            onClick={() => setDismissed(true)}
            disabled={dismissed}
          >
            Dismiss AI interpretation
          </Button>
        </div>
      </Tile>
    </section>
  );
}

function O3RefillRequest() {
  const [decision, setDecision] = useState(null);

  const aiLabel = makeAILabel({
    heading: 'Refill recommended',
    body: 'Recommended because the patient’s refill history and last visit note support continuing this medication unchanged. Nothing is sent to the pharmacy until confirmed.',
    kind: 'inline',
    size: 'xs',
  });

  return (
    <section className="anomaly-scenario">
      <LevelTag
        level="O3"
        title="Routine medication refill"
        requirement="Ship requirement: explicit Confirm or Cancel before the action takes effect."
      />
      <Tile className="anomaly-tile">
        <div className="anomaly-tile-header">
          <p className="anomaly-metric">Patient: M. Chen &mdash; Lisinopril 10mg</p>
          {aiLabel}
        </div>
        <p className="anomaly-note">
          Recommended action: approve a 90-day refill, no dosage change.
        </p>
        {!decision && (
          <div className="anomaly-controls">
            <Button kind="primary" size="sm" onClick={() => setDecision('confirmed')}>
              Confirm
            </Button>
            <Button kind="secondary" size="sm" onClick={() => setDecision('cancelled')}>
              Cancel
            </Button>
          </div>
        )}
        {decision && (
          <p className={`oversight-result ${decision}`}>
            {decision === 'confirmed'
              ? 'Refill sent to the pharmacy.'
              : 'Refill not sent. Chart flagged for clinician review.'}
          </p>
        )}
      </Tile>
    </section>
  );
}

function O4DosageChange() {
  const [approver, setApprover] = useState('');
  const [confirmed, setConfirmed] = useState(false);

  const aiLabel = makeAILabel({
    heading: 'Dosage change recommended',
    body: 'Recommended based on the patient’s latest renal function panel. Requires sign-off from a named prescribing clinician before it can be ordered.',
    kind: 'inline',
    size: 'xs',
  });

  return (
    <section className="anomaly-scenario">
      <LevelTag
        level="O4"
        title="Recommended dosage change"
        requirement="Ship requirement: confirm action stays disabled until a specific named approver is selected."
      />
      <Tile className="anomaly-tile">
        <div className="anomaly-tile-header">
          <p className="anomaly-metric">Patient: D. Patel &mdash; Metformin</p>
          {aiLabel}
        </div>
        <p className="anomaly-note">
          Recommended action: reduce dose from 1000mg to 500mg twice daily given
          declining eGFR.
        </p>
        <div className="anomaly-controls">
          <Select
            id="health-o4-approver"
            labelText="Prescribing clinician"
            value={approver}
            onChange={(e) => setApprover(e.target.value)}
          >
            <SelectItem value="" text="Select a clinician" />
            {APPROVERS.map((name) => (
              <SelectItem key={name} value={name} text={name} />
            ))}
          </Select>
          <Button
            kind="primary"
            size="sm"
            disabled={!approver || confirmed}
            onClick={() => setConfirmed(true)}
          >
            Order dosage change
          </Button>
        </div>
        {confirmed && (
          <p className="oversight-result confirmed">
            Dosage change ordered by {approver}.
          </p>
        )}
      </Tile>
    </section>
  );
}

function O5DeteriorationRisk() {
  const [reviewer1, setReviewer1] = useState('');
  const [reviewer2, setReviewer2] = useState('');
  const [auditLog, setAuditLog] = useState([]);
  const [unlocked, setUnlocked] = useState(false);

  const bothSelected = reviewer1 && reviewer2;
  const distinctReviewers = bothSelected && reviewer1 !== reviewer2;

  const logApproval = (label, name) => {
    setAuditLog((log) => [
      ...log,
      { label, name, timestamp: new Date().toLocaleTimeString() },
    ]);
  };

  const handleReviewer1Change = (e) => {
    const name = e.target.value;
    setReviewer1(name);
    setUnlocked(false);
    if (name) logApproval('Clinician 1', name);
  };

  const handleReviewer2Change = (e) => {
    const name = e.target.value;
    setReviewer2(name);
    setUnlocked(false);
    if (name) logApproval('Clinician 2', name);
  };

  const handleUnlock = () => {
    setUnlocked(true);
    logApproval('Escalation authorized', `${reviewer1} + ${reviewer2}`);
  };

  const aiLabel = makeAILabel({
    heading: 'Critical risk flagged',
    body: 'Flagged because this patient’s vitals trend matches an early sepsis pattern from the early-warning model. Requires two different named clinicians before rapid response is activated.',
    kind: 'inline',
    size: 'xs',
  });

  return (
    <section className="anomaly-scenario">
      <LevelTag
        level="O5"
        title="Critical deterioration risk"
        requirement="Ship requirement: two different named reviewers required to unlock, with each approval logged to a visible audit trail."
      />
      <Tile className="anomaly-tile">
        <div className="anomaly-tile-header">
          <p className="anomaly-metric">Patient: S. Novak &mdash; Ward 4B, bed 12</p>
          {aiLabel}
        </div>
        <p className="anomaly-value">Early-warning score: 9 (high)</p>
        <p className="anomaly-note">
          Recommended action: activate rapid response team.
        </p>
        <div className="anomaly-controls">
          <Select
            id="health-o5-reviewer1"
            labelText="Clinician 1"
            value={reviewer1}
            onChange={handleReviewer1Change}
          >
            <SelectItem value="" text="Select a clinician" />
            {APPROVERS.map((name) => (
              <SelectItem key={name} value={name} text={name} />
            ))}
          </Select>
          <Select
            id="health-o5-reviewer2"
            labelText="Clinician 2"
            value={reviewer2}
            onChange={handleReviewer2Change}
          >
            <SelectItem value="" text="Select a clinician" />
            {APPROVERS.map((name) => (
              <SelectItem key={name} value={name} text={name} />
            ))}
          </Select>
          <Button
            kind="primary"
            size="sm"
            disabled={!distinctReviewers || unlocked}
            onClick={handleUnlock}
            renderIcon={distinctReviewers ? Unlocked : Locked}
          >
            {unlocked ? 'Unlocked' : 'Unlock action'}
          </Button>
        </div>
        {bothSelected && !distinctReviewers && (
          <p className="oversight-result cancelled">
            Clinician 1 and Clinician 2 must be different people.
          </p>
        )}
        {unlocked && (
          <p className="oversight-result confirmed">
            Rapid response team activated.
          </p>
        )}
        <div className="audit-trail">
          <h4>Audit trail</h4>
          {auditLog.length === 0 ? (
            <p className="audit-empty">No approvals logged yet.</p>
          ) : (
            <ul>
              {auditLog.map((entry, i) => (
                <li key={i}>
                  <span className="audit-timestamp">{entry.timestamp}</span>
                  <span>
                    {entry.label}: {entry.name}
                  </span>
                </li>
              ))}
            </ul>
          )}
        </div>
      </Tile>
    </section>
  );
}

function HealthcareDemo() {
  return (
    <div className="dashboard-demo">
      <p className="app-subtitle">
        Clinical decision-support patterns tend to need a stronger floor than
        other domains &mdash; O1 here is disclosure-only per the ship
        requirement, but note that many clinical review boards would still
        require a licensed clinician to see any AI output before it reaches a
        patient record, even at the lowest risk tier.
      </p>
      <O1VisitSummary />
      <O2LabInterpretation />
      <O3RefillRequest />
      <O4DosageChange />
      <O5DeteriorationRisk />
    </div>
  );
}

export default HealthcareDemo;
